<a href="https://colab.research.google.com/github/chtariqiqbal406-pixel/Python_project/blob/main/My_Numpy_file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as tr
ar_1=tr.array([1,3,5,6,7,9])
ar_2=tr.array([2,5,3,6,8,1])
print("My 1st Array:",ar_1)
print("My 2nd Array:",ar_2)
print("Multiplication:",tr.multiply(ar_1,ar_2))
print("Addition:",tr.add(ar_1,ar_2))
print("Subtraction:",tr.subtract(ar_1,ar_2))
print("Division:",tr.divide(ar_1,ar_2))
print("Line Space:",tr.linspace(1,15,5))


My 1st Array: [1 3 5 6 7 9]
My 2nd Array: [2 5 3 6 8 1]
Multiplication: [ 2 15 15 36 56  9]
Addition: [ 3  8  8 12 15 10]
Subtraction: [-1 -2  2  0 -1  8]
Division: [0.5        0.6        1.66666667 1.         0.875      9.        ]
Line Space: [ 1.   4.5  8.  11.5 15. ]


1 Create a NumPy array from a Python list [1, 2, 3, 4, 5].
 Print the array and its type.

In [2]:
import numpy as tt
ar_1=tt.array([1,2,3,4,5])
print("My Array:",ar_1)
print("Type:",type(ar_1))

My Array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>


2 Use np.arange() to create a 1D array of numbers from 10 to 50.
 Print the shape and size of the array.

In [ ]:
arrange=tt.arange(10,50)
print("My Array:",arrange)

My Array: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


3 Create a 2D NumPy array of shape (3, 4) filled with zeros using np.zeros().
 Convert all zeros into fives.

In [ ]:
ar_2d=tt.array([[2,3,4,5],[6,7,8,9],[4,7,1,3]])
print("2D Ayyar:\n" ,ar_2d)
print("Shape:",ar_2d.shape)
print("Size:",ar_2d.size)
print('Data type:', ar_2d.dtype)
print("Demention number",ar_2d.ndim)
print(f"Zero arry:\n{(tt.zeros((3,4)))}")
print("after conversion into 5:\n",tt.zeros((3,4))+5)

2D Ayyar:
 [[2 3 4 5]
 [6 7 8 9]
 [4 7 1 3]]
Shape: (3, 4)
Size: 12
Data type: int64
Demention number 2
Zero arry:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
after conversion into 5:
 [[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]


4 Generate a 1D array of 15 random integers between 1 and 100 using np.random.randint().
 Find the maximum, minimum, and mean values.

In [ ]:
array=tt.random.randint(1,100,15)
print("My Array:",array)
print("Maximum:",array.max())
print("Minimum:",array.min())
print("Mean:",array.mean())
print("Variance:",array.var())
print("SD:",array.std())


My Array: [ 3 13 74 30 26 61 29 26 72 31 19 17 69 96 70]
Maximum: 96
Minimum: 3
Mean: 42.4
Variance: 744.9066666666666
SD: 27.292978339980902


5 Create a NumPy array of numbers from 1 to 20.
 Extract only the even numbers using slicing or boolean indexing.
 Reverse the array using slicing.

In [ ]:
 Ary=tt.arange(1,21)
 print("Array:",Ary)
 print("Even Number:",Ary[1::2])
 print("Reverse:",Ary[::-1])


Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Even Number: [ 2  4  6  8 10 12 14 16 18 20]
Reverse: [20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


6 Create a NumPy array [10, 20, 30, 40, 50].
 Print the first element
 Print the last element

In [ ]:
arry=tt.array([10,20,30,40,50])
print("Array:",arry)
print('First Element:',tt.array([arry[0]]))
print('Last Element:',tt.array([arry[-1]]))

Array: [10 20 30 40 50]
First Element: [10]
Last Element: [50]


7 Make a 2D array of shape (4, 4) with numbers from 1 to 16.
 Extract the first two rows and last two columns.
 Replace the diagonal elements with 0.

In [3]:
arry=tt.array([[2,3,4,6],[6,7,8,9],[9,10,11,12],[12,13,14,15]])
print(f"Array 4*4,\n{arry}")
print()
print("Matrix 1st 2 rows and last 2 column \n",arry[:2, 2:])
print()
tt.fill_diagonal(arry,0)
print(arry)

Array 4*4,
[[ 2  3  4  6]
 [ 6  7  8  9]
 [ 9 10 11 12]
 [12 13 14 15]]

Matrix 1st 2 rows and last 2 column 
 [[4 6]
 [8 9]]

[[ 0  3  4  6]
 [ 6  0  8  9]
 [ 9 10  0 12]
 [12 13 14  0]]


8 Create an array of 25 random integers between 1 and 100.
 Sort the array using np.sort().

In [4]:
arry=tt.random.randint(1,100,25)
print("Array:",arry)
print("Sorted Array:",tt.sort(arry))

Array: [24 30 64 70 15 67 35 17  7 33 94 31 48 51 23 88 68 17 59 19 35 76 87 92
 55]
Sorted Array: [ 7 15 17 17 19 23 24 30 31 33 35 35 48 51 55 59 64 67 68 70 76 87 88 92
 94]


9 Create a 1D array of numbers from 1 to 10 and find:
 Maximum (np.max())
 Minimum (np.min())
 Sum (np.sum())

In [5]:
arry=tt.arange(1,11)
print("Array:",arry)
print("Maximum:",arry.max())
print("Minimum:",arry.min())
print("Sum:",arry.sum())

Array: [ 1  2  3  4  5  6  7  8  9 10]
Maximum: 10
Minimum: 1
Sum: 55


10Reshape a 1D array of 36 elements into a 2D array of shape (6, 6).
 Find the sum of each row and each column using np.sum() with axis.

In [10]:
arry=tt.arange(1,37)
print("Array:",arry)
print()
reshaped_arry = arry.reshape(6,6)
print("Reshape:\n",reshaped_arry)
print()
print("Sum of each row:\n",tt.sum(reshaped_arry,axis=1))
print()
print("Sum of each column:\n",tt.sum(reshaped_arry,axis=0))

Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]

Reshape:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Sum of each row:
 [ 21  57  93 129 165 201]

Sum of each column:
 [ 96 102 108 114 120 126]
